%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(login_pb).
-define(login_pb, true).

-define(login_pb_gpb_version, "4.10.5").

-ifndef('C2S_HEARTBEAT_PB_H').
-define('C2S_HEARTBEAT_PB_H', true).
-record(c2s_heartbeat,
        {
        }).
-endif.

-ifndef('S2C_HEARTBEAT_PB_H').
-define('S2C_HEARTBEAT_PB_H', true).
-record(s2c_heartbeat,
        {timestamp = 0          :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('C2S_LOGIN_PB_H').
-define('C2S_LOGIN_PB_H', true).
-record(c2s_login,
        {iSiteID = 0            :: integer() | undefined, % = 1, 32 bits
         iTerminalType = 0      :: integer() | undefined, % = 2, 32 bits
         iLoginType = 0         :: integer() | undefined, % = 3, 32 bits
         sAccount = <<>>        :: iodata() | undefined, % = 4
         sPassword = <<>>       :: iodata() | undefined, % = 5
         sMachine = <<>>        :: iodata() | undefined, % = 6
         sChannel = <<>>        :: iodata() | undefined % = 7
        }).
-endif.

-ifndef('S2C_LOGIN_PB_H').
-define('S2C_LOGIN_PB_H', true).
-record(s2c_login,
        {iCode = 0              :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('C2S_RE_LOGIN_PB_H').
-define('C2S_RE_LOGIN_PB_H', true).
-record(c2s_re_login,
        {iUserID = 0            :: integer() | undefined, % = 1, 32 bits
         sToken = <<>>          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('S2C_RE_LOGIN_PB_H').
-define('S2C_RE_LOGIN_PB_H', true).
-record(s2c_re_login,
        {iCode = 0              :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
