%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(player_pb).
-define(player_pb, true).

-define(player_pb_gpb_version, "4.10.5").

-ifndef('C2S_PLAYER_INFO_PB_H').
-define('C2S_PLAYER_INFO_PB_H', true).
-record(c2s_player_info,
        {
        }).
-endif.

-ifndef('S2C_PLAYER_INFO_PB_H').
-define('S2C_PLAYER_INFO_PB_H', true).
-record(s2c_player_info,
        {sNickName = <<>>       :: iodata() | undefined, % = 1
         iGameCoin = 0          :: integer() | undefined, % = 2, 32 bits
         iBankCoin = 0          :: integer() | undefined, % = 3, 32 bits
         sPhone = <<>>          :: iodata() | undefined, % = 4
         sIcon = <<>>           :: iodata() | undefined % = 5
        }).
-endif.

-endif.
